### Create a workspace (admin)

POST {{baseUrl}}/workspaces
Accept: {{contentType}}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "templateName": "{{workspaceTemplate}}",
  "properties": {
    "display_name": "my workspace",
    "description": "my workspace",
    "client_id": "{{clientId}}",
    "vm_size": "Standard_A1",
    "no_of_vms": 2
  }
}

### Create a workspace service (workspace owner)

POST {{baseUrl}}/workspaces/{{workspaceId}}/workspace-services
Accept: {{contentType}}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "templateName": "{{workspaceServiceTemplate}}",
  "properties": {
    "display_name": "my workspace service",
    "description": "my workspace service"
  }
}

### Create a user resource (workspace researcher)

POST {{baseUrl}}/workspaces/{{workspaceId}}/workspace-services/{{workspaceServiceId}}/user-resources
Accept: {{contentType}}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "templateName": "{{userResourceTemplate}}",
  "properties": {
    "display_name": "my user resource",
    "description": "my user resource"
  }
}

### Disable a workspace (admin)

PATCH {{baseUrl}}/workspaces/{{workspaceId}}
Accept: {{contentType}}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "enabled": false
}

### Delete a workspace (admin)

DELETE {{baseUrl}}/workspaces/{{workspaceId}}
Accept: {{contentType}}
Authorization: Bearer {{token}}

### Disable a workspace service (workspace owner)

PATCH {{baseUrl}}/workspaces/{{workspaceId}}/workspace-services/{{workspaceServiceId}}
Accept: {{contentType}}
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "enabled": false
}

### Delete a workspace service (workspace owner)

DELETE {{baseUrl}}/workspaces/{{workspaceId}}/workspace-services/{{workspaceServiceId}}
Accept: {{contentType}}
Authorization: Bearer {{token}}
