variable "tre_id" {}
variable "location" {}
variable "resource_group_name" {}
variable "resource_group_id" {}
variable "tre_workspace_tags" {}
variable "workspace_subnet_id" {}
variable "azure_monitor_dns_zone_id" {}
variable "azure_monitor_oms_opinsights_dns_zone_id" {}
variable "azure_monitor_ods_opinsights_dns_zone_id" {}
variable "azure_monitor_agentsvc_dns_zone_id" {}
variable "blob_core_dns_zone_id" {}
variable "enable_local_debugging" {}
variable "ws_unique_identifier_suffix" {}
