# syntax=docker/dockerfile-upstream:1.4.0
ARG DEBIAN_TAG=bookworm-slim
ARG DEBIAN_BASE_IMAGE=debian
FROM --platform=linux/amd64 ${DEBIAN_BASE_IMAGE}:${DEBIAN_TAG}

# PORTER_INIT

# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY --link . ${BUNDLE_DIR}/
