variable "workspace_id" {}
variable "tre_id" {}
variable "azureml_workspace_name" {}
variable "azureml_compute_cluster_name" {}
variable "inference_sp_client_id" {}
variable "inference_sp_client_secret" {}
variable "arm_client_id" {}
variable "arm_client_secret" {}
variable "arm_tenant_id" {}