FROM debian:stretch-slim

ARG BUNDLE_DIR

RUN apt-get update \
    && apt-get install -y ca-certificates \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install Azure CLI
RUN apt-get update \
    && apt-get install -y ca-certificates jq curl apt-transport-https lsb-release gnupg \
    && curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null \
    && AZ_REPO=$(lsb_release -cs) \
    && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | tee /etc/apt/sources.list.d/azure-cli.list \
    && apt-get update && apt-get -y install azure-cli \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Install Certbot
RUN apt-get update && apt-get install -y python3 python3-venv libaugeas0 \
    && python3 -m venv /opt/certbot/ \
    && /opt/certbot/bin/pip install --no-cache-dir --upgrade pip \
    && /opt/certbot/bin/pip install --no-cache-dir certbot \
    && apt-get clean -y && rm -rf /var/lib/apt/lists/*

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY . $BUNDLE_DIR
