IMPORT = "import"
EXPORT = "export"

DRAFT_STATUS = "draft"
SUBMITTED_STATUS = "submitted"
IN_REVIEW_STATUS = "in_review"
APPROVED_STATUS = "approved"
REJECTED_STATUS = "rejected"
CANCELLED_STATUS = "cancelled"
BLOCKED_STATUS = "blocked_by_scan"
FAILED_STATUS = "failed"

AIRLOCK_REQUEST = "airlockRequest"
AIRLOCK_REQUEST_STATUS = "status"
AIRLOCK_REQUEST_STATUS_MESSAGE = "statusMessage"
