# syntax=docker/dockerfile-upstream:1.4.0
FROM --platform=linux/amd64 debian:bullseye-slim

# PORTER_INIT

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

# sqlcmd is required for schemas initialization in AzureSynapse
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# ignore lint rule that requires `--no-install-recommends` to allow the microsoft packeges to get everything they need and clear it all up in the end
# hadolint ignore=DL3015
RUN apt-get update && apt-get install -y curl gnupg && \
  curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - && \
  echo 'deb https://packages.microsoft.com/debian/11/prod bullseye main'> /etc/apt/sources.list.d/prod.list && \
  apt-get update && apt-get -y install sqlcmd --no-install-recommends && \
  apt-get clean && rm -rf /var/lib/apt/lists/*

# Git is required for terraform_azurerm_environment_configuration
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get install -y git --no-install-recommends

# PostgreSql is required by Atlas
RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
    apt-get update && apt-get install -y postgresql-client gettext apache2-utils curl jq --no-install-recommends

# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY --link . ${BUNDLE_DIR}/
