---
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 7.3.0
    hooks:
      - id: flake8
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.2
    hooks:
      - id: codespell
  - repo: https://github.com/rbubley/mirrors-prettier
    rev: v3.5.0
    hooks:
      - id: prettier
        files: ^ui/app/
