variable "resource_name_prefix" {}
variable "tag" {} 
variable "location" {}
variable "address_space" {}
variable "default_address_space" {}
variable "inference_address_space" {}
variable "fw_address_space" {}
variable "username" {}
variable "password" {}
variable "allowedURLs" {}
variable "allowedInnerEyeURLs" {}
variable "allowedServiceTags" {}