variable "tre_id" {}
variable "location" {}
variable "resource_group_name" {}
variable "shared_subnet_id" {}
variable "azure_monitor_dns_zone_id" {}
variable "azure_monitor_oms_opinsights_dns_zone_id" {}
variable "azure_monitor_ods_opinsights_dns_zone_id" {}
variable "azure_monitor_agentsvc_dns_zone_id" {}
variable "blob_core_dns_zone_id" {}
variable "tre_core_tags" {}
variable "enable_local_debugging" {}
