CREATE SCHEMA ${SCHEMA_NAME}
AUTHORIZATION ${OHDSI_ADMIN_ROLE};

COMMENT ON SCHEMA ${SCHEMA_NAME} IS 'Schema containing tables to support WebAPI functionality';

GRANT USAGE ON SCHEMA ${SCHEMA_NAME} TO PUBLIC;

GRANT ALL ON SCHEMA ${SCHEMA_NAME} TO GROUP ${OHDSI_ADMIN_ROLE};

GRANT USAGE ON SCHEMA ${SCHEMA_NAME} TO GROUP ${OHDSI_APP_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT
INSERT,
SELECT,
UPDATE,
DELETE, REFERENCES,
        TRIGGER ON TABLES TO ${OHDSI_APP_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT
SELECT, USAGE ON SEQUENCES TO ${OHDSI_APP_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT EXECUTE ON FUNCTIONS TO ${OHDSI_APP_ROLE};

ALTER DEFAULT PRIVILEGES IN SCHEMA ${SCHEMA_NAME} GRANT USAGE ON TYPES TO ${OHDSI_APP_ROLE};
