#!/usr/bin/with-contenv sh
set -x
echo >&2 "starting oauth2-proxy"

cookiesecret=$(dd if=/dev/urandom bs=32 count=1 2>/dev/null | base64 | tr -d -- '\n' | tr -- '+/' '-_'; echo)

"${OAUTH2_PROXY_HOME}"/oauth2-proxy \
--provider oidc \
--skip-provider-button \
--cookie-secret "${cookiesecret}" \
--cookie-expire 0m \
--oidc-issuer-url "${OAUTH2_PROXY_OIDC_ISSUER_URL}" \
--upstream http://0.0.0.0:8080 \
--email-domain "${OAUTH2_PROXY_EMAIL_DOMAIN}" \
--redirect-url "${OAUTH2_PROXY_REDIRECT_URI}" --pass-host-header true \
--show-debug-on-error true --pass-authorization-header true --pass-user-headers true \
--http-address http://0.0.0.0:8085 \
--https-address https://0.0.0.0:8086 \
--cookie-secure true \
--reverse-proxy true \
--pass-access-token true \
--set-xauthrequest true \
--pass-basic-auth true \
--cookie-refresh 50m \
--insecure-oidc-allow-unverified-email true \
--oidc-groups-claim "roles" \
--oidc-email-claim "preferred_username" \
--scope "openid offline_access ${AUDIENCE}/user_impersonation profile"
