variable "tre_id" {}
variable "location" {}
variable "resource_group_name" {}
variable "firewall_private_ip_address" {}
variable "shared_subnet_id" {}
variable "resource_processor_subnet_id" {}
variable "web_app_subnet_id" {}
variable "app_gw_subnet_id" {}
variable "aci_subnet_id" {}