"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.resource_history_item import ResourceHistoryItem
from openapi_client.model.resource_type import ResourceType
globals()['ResourceHistoryItem'] = ResourceHistoryItem
globals()['ResourceType'] = ResourceType
from openapi_client.model.workspace import Workspace


class TestWorkspace(unittest.TestCase):
    """Workspace unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspace(self):
        """Test Workspace"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Workspace()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
