"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.shared_services_api import SharedServicesApi  # noqa: E501


class TestSharedServicesApi(unittest.TestCase):
    """SharedServicesApi unit test stubs"""

    def setUp(self):
        self.api = SharedServicesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_a_shared_service_api_shared_services_post(self):
        """Test case for create_a_shared_service_api_shared_services_post

        Create A Shared Service  # noqa: E501
        """
        pass

    def test_delete_shared_service_api_shared_services_shared_service_id_delete(self):
        """Test case for delete_shared_service_api_shared_services_shared_service_id_delete

        Delete Shared Service  # noqa: E501
        """
        pass

    def test_get_a_single_resource_operation_by_id_api_shared_services_shared_service_id_operations_operation_id_get(self):
        """Test case for get_a_single_resource_operation_by_id_api_shared_services_shared_service_id_operations_operation_id_get

        Get A Single Resource Operation By Id  # noqa: E501
        """
        pass

    def test_get_all_operations_for_a_resource_api_shared_services_shared_service_id_operations_get(self):
        """Test case for get_all_operations_for_a_resource_api_shared_services_shared_service_id_operations_get

        Get All Operations For A Resource  # noqa: E501
        """
        pass

    def test_get_all_shared_services_api_shared_services_get(self):
        """Test case for get_all_shared_services_api_shared_services_get

        Get All Shared Services  # noqa: E501
        """
        pass

    def test_get_shared_service_by_id_api_shared_services_shared_service_id_get(self):
        """Test case for get_shared_service_by_id_api_shared_services_shared_service_id_get

        Get Shared Service By Id  # noqa: E501
        """
        pass

    def test_invoke_action_on_a_shared_service_api_shared_services_shared_service_id_invoke_action_post(self):
        """Test case for invoke_action_on_a_shared_service_api_shared_services_shared_service_id_invoke_action_post

        Invoke Action On A Shared Service  # noqa: E501
        """
        pass

    def test_update_an_existing_shared_service_api_shared_services_shared_service_id_patch(self):
        """Test case for update_an_existing_shared_service_api_shared_services_shared_service_id_patch

        Update An Existing Shared Service  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
