"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.user_resource_templates_api import UserResourceTemplatesApi  # noqa: E501


class TestUserResourceTemplatesApi(unittest.TestCase):
    """UserResourceTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = UserResourceTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_user_resource_template_by_name_and_workspace_service_api_workspace_service_templates_service_template_name_user_resource_templates_user_resource_template_name_get(self):
        """Test case for get_user_resource_template_by_name_and_workspace_service_api_workspace_service_templates_service_template_name_user_resource_templates_user_resource_template_name_get

        Get User Resource Template By Name And Workspace Service  # noqa: E501
        """
        pass

    def test_get_user_resource_templates_applicable_to_the_workspace_service_template_api_workspace_service_templates_service_template_name_user_resource_templates_get(self):
        """Test case for get_user_resource_templates_applicable_to_the_workspace_service_template_api_workspace_service_templates_service_template_name_user_resource_templates_get

        Get User Resource Templates Applicable To The Workspace Service Template  # noqa: E501
        """
        pass

    def test_register_user_resource_template_api_workspace_service_templates_service_template_name_user_resource_templates_post(self):
        """Test case for register_user_resource_template_api_workspace_service_templates_service_template_name_user_resource_templates_post

        Register User Resource Template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
