"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.resource_template_information import ResourceTemplateInformation
globals()['ResourceTemplateInformation'] = ResourceTemplateInformation
from openapi_client.model.resource_template_information_in_list import ResourceTemplateInformationInList


class TestResourceTemplateInformationInList(unittest.TestCase):
    """ResourceTemplateInformationInList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResourceTemplateInformationInList(self):
        """Test ResourceTemplateInformationInList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ResourceTemplateInformationInList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
