"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.custom_action import CustomAction
from openapi_client.model.model_property import ModelProperty
from openapi_client.model.resource_type import ResourceType
globals()['CustomAction'] = CustomAction
globals()['ModelProperty'] = ModelProperty
globals()['ResourceType'] = ResourceType
from openapi_client.model.user_resource_template_in_response import UserResourceTemplateInResponse


class TestUserResourceTemplateInResponse(unittest.TestCase):
    """UserResourceTemplateInResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUserResourceTemplateInResponse(self):
        """Test UserResourceTemplateInResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UserResourceTemplateInResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
