"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.workspaces_api import WorkspacesApi  # noqa: E501


class TestWorkspacesApi(unittest.TestCase):
    """WorkspacesApi unit test stubs"""

    def setUp(self):
        self.api = WorkspacesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_a_workspace_api_workspaces_post(self):
        """Test case for create_a_workspace_api_workspaces_post

        Create A Workspace  # noqa: E501
        """
        pass

    def test_delete_workspace_api_workspaces_workspace_id_delete(self):
        """Test case for delete_workspace_api_workspaces_workspace_id_delete

        Delete Workspace  # noqa: E501
        """
        pass

    def test_get_a_single_resource_operation_by_id_api_workspaces_workspace_id_operations_operation_id_get(self):
        """Test case for get_a_single_resource_operation_by_id_api_workspaces_workspace_id_operations_operation_id_get

        Get A Single Resource Operation By Id  # noqa: E501
        """
        pass

    def test_get_all_operations_for_a_resource_api_workspaces_workspace_id_operations_get(self):
        """Test case for get_all_operations_for_a_resource_api_workspaces_workspace_id_operations_get

        Get All Operations For A Resource  # noqa: E501
        """
        pass

    def test_get_all_workspaces_api_workspaces_get(self):
        """Test case for get_all_workspaces_api_workspaces_get

        Get All Workspaces  # noqa: E501
        """
        pass

    def test_get_workspace_by_id_api_workspaces_workspace_id_get(self):
        """Test case for get_workspace_by_id_api_workspaces_workspace_id_get

        Get Workspace By Id  # noqa: E501
        """
        pass

    def test_invoke_action_on_a_workspace_api_workspaces_workspace_id_invoke_action_post(self):
        """Test case for invoke_action_on_a_workspace_api_workspaces_workspace_id_invoke_action_post

        Invoke Action On A Workspace  # noqa: E501
        """
        pass

    def test_update_an_existing_workspace_api_workspaces_workspace_id_patch(self):
        """Test case for update_an_existing_workspace_api_workspaces_workspace_id_patch

        Update An Existing Workspace  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
