"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.shared_service import SharedService
globals()['SharedService'] = SharedService
from openapi_client.model.shared_service_in_response import SharedServiceInResponse


class TestSharedServiceInResponse(unittest.TestCase):
    """SharedServiceInResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSharedServiceInResponse(self):
        """Test SharedServiceInResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SharedServiceInResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
