"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.shared_service_templates_api import SharedServiceTemplatesApi  # noqa: E501


class TestSharedServiceTemplatesApi(unittest.TestCase):
    """SharedServiceTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = SharedServiceTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_shared_service_template_by_name_api_shared_service_templates_shared_service_template_name_get(self):
        """Test case for get_shared_service_template_by_name_api_shared_service_templates_shared_service_template_name_get

        Get Shared Service Template By Name  # noqa: E501
        """
        pass

    def test_get_shared_service_templates_api_shared_service_templates_get(self):
        """Test case for get_shared_service_templates_api_shared_service_templates_get

        Get Shared Service Templates  # noqa: E501
        """
        pass

    def test_register_shared_service_template_api_shared_service_templates_post(self):
        """Test case for register_shared_service_template_api_shared_service_templates_post

        Register Shared Service Template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
