"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import unittest

import openapi_client
from openapi_client.api.workspace_service_templates_api import WorkspaceServiceTemplatesApi  # noqa: E501


class TestWorkspaceServiceTemplatesApi(unittest.TestCase):
    """WorkspaceServiceTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = WorkspaceServiceTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_workspace_service_template_by_name_api_workspace_service_templates_service_template_name_get(self):
        """Test case for get_workspace_service_template_by_name_api_workspace_service_templates_service_template_name_get

        Get Workspace Service Template By Name  # noqa: E501
        """
        pass

    def test_get_workspace_service_templates_api_workspace_service_templates_get(self):
        """Test case for get_workspace_service_templates_api_workspace_service_templates_get

        Get Workspace Service Templates  # noqa: E501
        """
        pass

    def test_register_workspace_service_template_api_workspace_service_templates_post(self):
        """Test case for register_workspace_service_template_api_workspace_service_templates_post

        Register Workspace Service Template  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
