"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.workspace import Workspace
globals()['Workspace'] = Workspace
from openapi_client.model.workspaces_in_list import WorkspacesInList


class TestWorkspacesInList(unittest.TestCase):
    """WorkspacesInList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWorkspacesInList(self):
        """Test WorkspacesInList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = WorkspacesInList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
