"""
    Azure TRE API

    Welcome to the Azure TRE API - for more information about templates and workspaces see the [Azure TRE documentation](https://microsoft.github.io/AzureTRE)  # noqa: E501

    The version of the OpenAPI document: 0.2.14
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import openapi_client
from openapi_client.model.operation import Operation
globals()['Operation'] = Operation
from openapi_client.model.operation_in_list import OperationInList


class TestOperationInList(unittest.TestCase):
    """OperationInList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperationInList(self):
        """Test OperationInList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OperationInList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
