FROM debian:bullseye-slim

# Install git - required for terraform_azurerm_environment_configuration
RUN apt-get update && apt-get install --no-install-recommends -y git \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*
 
# PORTER_INIT

SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt \
    apt-get update \
    && apt-get install --no-install-recommends -y jq curl ca-certificates

RUN export PORTER_HOME=/home/"${USER}"/.porter \
    && curl -L https://cdn.porter.sh/latest/install-linux.sh | bash \
    && "${PORTER_HOME}"/porter mixin install docker

ENV PATH /home/$USER/.porter/:$PATH

# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY --link . ${BUNDLE_DIR}/
