variable "workspace_id" {}
variable "tre_id" {}
variable "arm_client_id" {}
variable "arm_client_secret" {}
variable "arm_tenant_id" {}
variable "arm_use_msi" {}
variable "mgmt_resource_group_name" {}
variable "mgmt_acr_name" {}
variable "image_name" {}
variable "image_tag" {}
variable "guac_disable_copy" {}
variable "guac_disable_paste" {}
variable "guac_enable_drive" {}
variable "guac_drive_name" {}
variable "guac_drive_path" {}
variable "guac_disable_download" {}
variable "is_exposed_externally" {}
variable "tre_resource_id" {}
