# RG
CORE_RG_NAME = "rg-{}"
WS_RG_NAME = "rg-{}-ws-{}"

# Import
STORAGE_ACCOUNT_NAME_IMPORT_EXTERNAL = "stalimex{}"
STORAGE_ACCOUNT_NAME_IMPORT_INPROGRESS = "stalimip{}"
STORAGE_ACCOUNT_NAME_IMPORT_APPROVED = "stalimappws{}"
STORAGE_ACCOUNT_NAME_IMPORT_REJECTED = "stalimrej{}"

# Export
STORAGE_ACCOUNT_NAME_EXPORT_INTERNAL = "stalexintws{}"
STORAGE_ACCOUNT_NAME_EXPORT_INPROGRESS = "stalexipws{}"
STORAGE_ACCOUNT_NAME_EXPORT_APPROVED = "stalexapp{}"
STORAGE_ACCOUNT_NAME_EXPORT_REJECTED = "stalexrejws{}"

# Stages
STAGE_SUBMITTED = "submitted"
STAGE_APPROVED = "approved"
STAGE_REJECTED = "rejected"
STAGE_BLOCKED = "blocked"
