# RG
CORE_RG_NAME = "rg-{}"
WS_RG_NAME = "rg-{}-ws-{}"

# Import
STORAGE_ACCOUNT_NAME_IMPORT_EXTERNAL = "stalimex{}"
STORAGE_ACCOUNT_NAME_IMPORT_INPROGRESS = "stalimip{}"

# Export
STORAGE_ACCOUNT_NAME_EXPORT_INTERNAL = "stalexintws{}"
STORAGE_ACCOUNT_NAME_EXPORT_INPROGRESS = "stalexipws{}"

# Stages
STAGE_SUBMITTED = "submitted"
STAGE_APPROVED = "approved"
STAGE_REJECTED = "rejected"
STAGE_BLOCKED ="blocked"