#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
E2E_ROOT="${SCRIPT_DIR}/.."
ENV_FILE="${E2E_ROOT}/.env"

APP_DISPLAY_NAME="${APP_DISPLAY_NAME:-Guacamole E2E $(date +%Y%m%d%H%M%S)}"
REDIRECT_URI="${REDIRECT_URI:-http://localhost:8080/oauth2/callback}"
EMAIL_DOMAIN="${EMAIL_DOMAIN:-*}"
SECRET_DISPLAY_NAME="${SECRET_DISPLAY_NAME:-GuacamoleE2ESecret}"

if ! command -v az >/dev/null 2>&1; then
  echo "Azure CLI (az) is required" >&2
  exit 1
fi

if ! az account show >/dev/null 2>&1; then
  echo "Run 'az login' before executing this script" >&2
  exit 1
fi

if ! command -v uuidgen >/dev/null 2>&1; then
  echo "Installing uuid-runtime package to provide uuidgen..."
  sudo apt-get update -qq
  sudo apt-get install -yqq uuid-runtime
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "Installing jq for JSON manipulation..."
  sudo apt-get update -qq
  sudo apt-get install -yqq jq
fi

tenant_id="$(az account show --query tenantId -o tsv)"

echo "Creating Azure AD application '${APP_DISPLAY_NAME}' in tenant ${tenant_id}..."
app_id="$(az ad app create \
  --display-name "${APP_DISPLAY_NAME}" \
  --sign-in-audience AzureADMyOrg \
  --web-redirect-uris "${REDIRECT_URI}" \
  --query appId -o tsv)"

audience="api://${app_id}"

az ad app update --id "${app_id}" --identifier-uris "${audience}" >/dev/null

echo "Setting app to use v2.0 tokens..."
az ad app update --id "${app_id}" --set "api.requestedAccessTokenVersion=2" >/dev/null

echo "Adding user_impersonation scope to ${app_id}..."
scope_id="$(uuidgen)"
api_payload="$(jq -nc --arg id "${scope_id}" '{
  oauth2PermissionScopes: [
    {
      adminConsentDescription: "Allow the app to access Guacamole on behalf of the signed-in user.",
      adminConsentDisplayName: "Access Guacamole",
      id: $id,
      isEnabled: true,
      type: "User",
      userConsentDescription: "Allow access to Guacamole.",
      userConsentDisplayName: "Access Guacamole",
      value: "user_impersonation"
    }
  ]
}')"
az ad app update --id "${app_id}" --set "api=${api_payload}" >/dev/null

echo "Adding app roles (WorkspaceOwner, WorkspaceResearcher, AirlockManager)..."
role_owner_id="$(uuidgen)"
role_researcher_id="$(uuidgen)"
role_airlock_id="$(uuidgen)"
roles_payload="$(jq -nc \
  --arg owner_id "${role_owner_id}" \
  --arg researcher_id "${role_researcher_id}" \
  --arg airlock_id "${role_airlock_id}" \
  '[
    {
      allowedMemberTypes: ["User"],
      description: "Workspace Owner role for Guacamole access",
      displayName: "WorkspaceOwner",
      id: $owner_id,
      isEnabled: true,
      value: "WorkspaceOwner"
    },
    {
      allowedMemberTypes: ["User"],
      description: "Workspace Researcher role for Guacamole access",
      displayName: "WorkspaceResearcher",
      id: $researcher_id,
      isEnabled: true,
      value: "WorkspaceResearcher"
    },
    {
      allowedMemberTypes: ["User"],
      description: "Airlock Manager role for Guacamole access",
      displayName: "AirlockManager",
      id: $airlock_id,
      isEnabled: true,
      value: "AirlockManager"
    }
  ]')"
az ad app update --id "${app_id}" --set "appRoles=${roles_payload}" >/dev/null

echo "Creating service principal and granting admin consent..."
az ad sp create --id "${app_id}" >/dev/null
az ad app permission admin-consent --id "${app_id}" >/dev/null 2>&1 || true

echo "Assigning WorkspaceResearcher role to current user..."
current_user_id="$(az ad signed-in-user show --query id -o tsv)"
sp_object_id="$(az ad sp show --id "${app_id}" --query id -o tsv)"
az rest --method POST \
  --uri "https://graph.microsoft.com/v1.0/servicePrincipals/${sp_object_id}/appRoleAssignedTo" \
  --headers "Content-Type=application/json" \
  --body "{
    \"principalId\": \"${current_user_id}\",
    \"resourceId\": \"${sp_object_id}\",
    \"appRoleId\": \"${role_researcher_id}\"
  }" >/dev/null 2>&1 || echo "Note: Role assignment may already exist or require retry"

echo "Creating client secret '${SECRET_DISPLAY_NAME}'..."
client_secret="$(az ad app credential reset \
  --id "${app_id}" \
  --display-name "${SECRET_DISPLAY_NAME}" \
  --query password -o tsv)"

# Azure AD v2.0 discovery returns issuer without trailing slash
issuer_url="https://login.microsoftonline.com/${tenant_id}/v2.0"
jwks_url="https://login.microsoftonline.com/${tenant_id}/discovery/v2.0/keys"

if [ -f "${ENV_FILE}" ]; then
  cp "${ENV_FILE}" "${ENV_FILE}.bak.$(date +%s)"
fi

cat >"${ENV_FILE}" <<EOF
# Auto-generated by scripts/setup-azure-auth.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
GUAC_OIDC_TENANT_ID=${tenant_id}
GUAC_OIDC_CLIENT_ID=${app_id}
GUAC_OIDC_CLIENT_SECRET=${client_secret}
GUAC_OIDC_REDIRECT_URI=${REDIRECT_URI}
GUAC_OIDC_EMAIL_DOMAIN=${EMAIL_DOMAIN}
GUAC_OIDC_ISSUER_URL=${issuer_url}
GUAC_OIDC_JWKS_URL=${jwks_url}
GUAC_OIDC_AUDIENCE=${app_id}
EOF

cat <<EOF

Azure AD configuration written to ${ENV_FILE}.
Exported variables:
  GUAC_OIDC_TENANT_ID
  GUAC_OIDC_CLIENT_ID
  GUAC_OIDC_CLIENT_SECRET
  GUAC_OIDC_REDIRECT_URI
  GUAC_OIDC_EMAIL_DOMAIN
  GUAC_OIDC_ISSUER_URL
  GUAC_OIDC_JWKS_URL
  GUAC_OIDC_AUDIENCE

To use these values with Docker Compose:
  cd "${E2E_ROOT}" && ./run-tests.sh up

To run the full automated test flow (provision, test, cleanup):
  cd "${E2E_ROOT}" && ./run-tests.sh full

Created app registration with roles:
  Display name : ${APP_DISPLAY_NAME}
  Application ID : ${app_id}
  Tenant ID : ${tenant_id}
  App Roles : WorkspaceOwner, WorkspaceResearcher, AirlockManager

IMPORTANT: The current user has been assigned the WorkspaceResearcher role.
           Tokens obtained for this app will now include the 'roles' claim.
           You may need to wait 5-10 minutes for role assignments to propagate.
EOF
