variable "tre_id" {}
variable "location" {}
variable "acr_id" {}
variable "resource_group_name" {}
variable "resource_processor_subnet_id" {}
variable "resource_processor_vmss_porter_image_repository" {}
variable "resource_processor_vmss_porter_image_tag" {}
variable "docker_registry_server" {}
variable "service_bus_connection_string" {}
variable "service_bus_resource_request_queue" {}
variable "service_bus_deployment_status_update_queue" {}
variable "resource_processor_client_id" {}
variable "resource_processor_client_secret" {}
variable "mgmt_storage_account_name" {}
variable "mgmt_resource_group_name" {}
variable "terraform_state_container_name" {}
variable "app_insights_connection_string" {}