# syntax=docker/dockerfile-upstream:1.4.0
FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y git

# PORTER_INIT

RUN rm -f /etc/apt/apt.conf.d/docker-clean; echo 'Binary::apt::APT::Keep-Downloaded-Packages "true";' > /etc/apt/apt.conf.d/keep-cache

# PORTER_MIXINS

RUN apt-get remove -y git

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY --link . ${BUNDLE_DIR}/
