variable "workspace_id" {}
variable "tre_id" {}
variable "arm_client_id" {}
variable "arm_client_secret" {}
variable "arm_tenant_id" {}
variable "arm_use_msi" {}
variable "acr_name" {}
variable "mgmt_resource_group_name" {}
variable "guacamole_image_tag" {}