# syntax=docker/dockerfile-upstream:1.4.0
FROM debian:bullseye-slim

# Install git - required for terraform_azurerm_environment_configuration 
RUN apt-get update && apt-get install --no-install-recommends -y git \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

# PORTER_INIT

# PORTER_MIXINS

# Use the BUNDLE_DIR build argument to copy files into the bundle
COPY --link . ${BUNDLE_DIR}/
