name: flag_external_pr

on:  # yamllint disable-line rule:truthy
  pull_request_target:
    types: [opened] # only run on new PRs
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
    # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment

jobs:
  check_author:
    name: Check PR author
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      # Ensure we have the script file for the github-script action to use
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - id: check_command
        name: Check for a command using GitHub script
        uses: actions/github-script@v7
        with:
          result-encoding: string
          script: |
            const script = require('./.github/scripts/build.js')
            await script.labelAsExternalIfAuthorDoesNotHaveWriteAccess({core, context, github});
