name: flag_external_pr

on:
  pull_request_target:
    types: [opened] # only run on new PRs
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issue_comment
    # https://docs.github.com/en/developers/webhooks-and-events/webhooks/webhook-events-and-payloads#issue_comment

jobs:
  check_author:
    name: Check PR author
    runs-on: ubuntu-latest
    steps:
      - id: check_command
        name: Check for a command using GitHub script
        uses: actions/github-script@v6
        with:
          result-encoding: string
          script: |
            // Previously, we attempted to use github.event.comment.author_association to check for OWNER or COLLABORATOR
            // Unfortunately, that always shows MEMBER if you are in the microsoft org and have that set to publicly visible
            // (Can check via https://github.com/orgs/microsoft/people?query=<username>)
            // https://docs.github.com/en/rest/reference/collaborators#check-if-a-user-is-a-repository-collaborator
            const username = context.payload.pull_request.user.login;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            let userHasWriteAccess = false;
            try {
              console.log(`Checking if user "${username}" has write access to ${owner}/${owner} ...`)
              const result = await github.request('GET /repos/{owner}/{repo}/collaborators/{username}', {
                owner,
                repo,
                username
              });
              userHasWriteAccess = result.status === 204;
              console.log("success")
              console.log(result);
            } catch (err) {
              console.log("error")
              console.log(err);
              if (err.status === 404){
                console.log("User not found in collaborators");
              } else {
                console.log(`Error checking if user has write access: ${err.status} (${err.response.data.message}) `)
              }
            }
            console.log("User has write access: " + userHasWriteAccess);

            if (!userHasWriteAccess) {
              console.log("Adding external label to PR " + context.payload.pull_request.number)
              github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: context.payload.pull_request.number,
                labels: ['external']
              });
            }
